# Generated by Django 5.0.2 on 2024-04-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Djangotrain_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trains',
        ),
    ]
