# Generated by Django 5.0.2 on 2024-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangotrain_app', '0004_alter_trains_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='ligne',
            field=models.IntegerField(null=True),
        ),
    ]
